[tool.poetry]
name = "hwcert-errbot"
version = "0.1.0"
description = ""
authors = ["Jonathan Cave <jonathan.cave@canonical.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
errbot = "^6.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
