from enum import Enum


class ArtefactBuildEnvironmentReviewDecision(str, Enum):
    APPROVED_ALL_TESTS_PASS = "APPROVED_ALL_TESTS_PASS"
    APPROVED_CUSTOMER_PREREQUISITE_FAIL = "APPROVED_CUSTOMER_PREREQUISITE_FAIL"
    APPROVED_FAULTY_HARDWARE = "APPROVED_FAULTY_HARDWARE"
    APPROVED_INCONSISTENT_TEST = "APPROVED_INCONSISTENT_TEST"
    APPROVED_UNSTABLE_PHYSICAL_INFRA = "APPROVED_UNSTABLE_PHYSICAL_INFRA"
    REJECTED = "REJECTED"

    def __str__(self) -> str:
        return str(self.value)
