on:
  push:
    paths:
      - 'test/**'
      - 'config/**'
      - 'plugins/**'
      - '.github/workflows/lint.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: [self-hosted, linux, large, noble, x64]
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Install dependencies
        run: sudo snap install --classic astral-uv
      - name: Run linters
        run: |
          uv tool run ruff check
          uv tool run ruff format --check --diff
