name: Publish OCI Image and charm

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build-and-publish-image:
    runs-on: [self-hosted, linux, xlarge, jammy, x64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          config-inline: |
            [registry."docker.io"]
              mirrors = ["https://github-runner-dockerhub-cache.canonical.com:5000"]

      - name: Log in to GitHub Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          file: ./Dockerfile
          tags: ghcr.io/${{ github.repository_owner }}/certification-errbot:latest

  build-and-push-charm:
    permissions:
      contents: write # workflow pushes a tag
      packages: read
    runs-on: [self-hosted, linux, xlarge, jammy, x64]
    needs:
      - build-and-publish-image
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GitHub Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Upload charm to charmhub
        uses: canonical/charming-actions/upload-charm@3d1aae2686723b4f25d1be5cc78bfe147f7f100d
        with:
          charm-path: "charm"
          credentials: "${{ secrets.CHARMHUB_TOKEN }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          upload-image: "true"
